export const projects = [
	{
		id: 11,
		year: 2026,
		name: 'SkillBoost Academy',
		category: 'Integration',
		company: 'Personal',
		technologies: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Auth.js'],
		link: 'www.celpipskillboostacademy.com',
	},
	{
		id: 0,
		year: 2026,
		name: 'My Auditor',
		category: 'Integration',
		company: 'Personal',
		technologies: ['Next.js', 'TypeScript', 'Tailwind CSS'],
		link: 'www.myauditor.live',
	},
	{
		id: 1,
		year: 2026,
		name: 'Click It Raffle Draw system',
		category: 'Integration',
		company: 'Udala Solutions',
		technologies: ['Next.js', 'Javascript', 'tailwind css'],
		link: 'click-it-frontend.vercel.app',
	},
	{
		id: 2,
		year: 2026,
		name: 'Rezinos',
		category: 'Integration',
		company: 'Udala Solutions',
		technologies: ['Next.js', 'Javascript', 'tailwind css', 'Framer Motion'],
		link: 'www.rezinos.com',
	},
	{
		id: 3,
		year: 2026,
		name: 'Rezino Skincare',
		category: 'Integration',
		company: 'Udala Solutions',
		technologies: ['Next js', 'Typescript', 'Redux', 'React Query'],
		link: 'www.rezino-skincare.vercel.app/',
	},
	{
		id: 4,
		year: 2025,
		name: 'Salario Marketing Page',
		category: 'Integration',
		company: 'Personal',
		technologies: ['React js', 'Bootstrap css'],
		link: 'https://salariopay.com',
	},
	{
		id: 6,
		year: 2025,
		name: 'Leewo Jones Photography',
		category: 'Design',
		company: 'Personal',
		technologies: ['React', 'Golang', 'SQLlite', 'Tailwind', 'Framer Motion'],
		link: 'www.leewo-jones.vercel.app/',
	},

	{
		id: 7,
		year: 2024,
		name: 'Faradays project',
		category: 'Design',
		company: 'Personal',
		technologies: ['React Js', 'Bootstrap CSS', 'Javascript'],
		link: 'www.faradays-projects.vercel.app',
	},
	{
		id: 8,
		year: 2024,
		name: 'Tamsey Finance Inc',
		category: 'Design',
		company: 'Personal',
		technologies: ['React js', 'Tailwind css', 'Vite'],
		link: 'www.brookfield-project.vercel.app',
	},
	{
		id: 9,
		year: 2024,
		name: 'Trevor Project',
		category: 'Design',
		company: 'Personal',
		technologies: ['React Js', 'Framer Motion', 'Tailwind CSS'],
		link: 'www.trevor-project-six.vercel.app',
	},
	{
		id: 10,
		year: 2023,
		name: 'Wfj Lawfirm',
		category: 'Design',
		company: 'Personal',
		technologies: ['React Js', 'Framer Motion', 'Tailwind CSS'],
		link: 'www.wfjlawfirm.vercel.app',
	},
];

export const experiences = [
	{
		period: 'May 2024 – Present',
		title: 'Frontend Engineer',
		company: 'Salariopay',
		companyUrl: 'https://salariopay.com',
		description:
			'Shipped a full-featured expense management and payment system from zero, giving employers end-to-end control over employee and vendor reimbursements — now a core operational workflow across the platform. Closed the gap between design specs and production by co-building pixel-accurate, high-performance payroll and HR interfaces with designers and backend engineers. Established the API integration patterns and responsive design conventions that now serve as the shared baseline across all user-facing features.',
		technologies: [
			'React',
			'Redux',
			'TypeScript',
			'JavaScript',
			'Tailwind CSS',
			'jQuery',
			'Next.js',
			'Bootstrap CSS',
		],
	},
	{
		period: 'March 2023 – Dec 2024',
		title: 'Software Developer',
		company: 'Metro Health HMO',
		companyUrl: 'https://metrohealthhmo.com',
		description:
			'Delivered a proprietary internal operations platform from the ground up, replacing manual, siloed workflows and consolidating multi-department processes into a single system that measurably improved business throughput. Digitised the full employee onboarding pipeline with an end-to-end HR intake system, eliminating paper-based processes across the organisation. Launched a real-time hospital wait-time tracker deployed across HMO locations, surfacing systemic bottlenecks that drove reductions in enrollee wait times and gave management actionable visibility into care delivery.',
		technologies: [
			'TypeScript',
			'React',
			'Node.js',
			'Next.js',
			'Bootstrap CSS',
			'Tailwind CSS',
		],
	},
	{
		period: 'Jan 2022 – Dec 2022',
		title: 'Software Engineering Trainee',
		company: 'ALX Africa',
		companyUrl: 'https://www.alxafrica.com',
		description:
			'Graduated from an intensive 12-month, project-based engineering programme, building and deploying multiple production-grade applications across C, Python, JavaScript, and SQL stacks, covering both backend systems and modern frontend frameworks. Developed an aggregator platform for bus transport systems, enabling users to discover routes, compare options, and book bus services seamlessly.',
		technologies: [
			'C',
			'TypeScript',
			'JavaScript',
			'Python',
			'SQL',
			'Bootstrap CSS',
			'React',
		],
	},
];
