export const projects = [
	{
		id: 0,
		year: 2026,
		name: 'My Auditor',
		category: 'Integration',
		company: 'Personal',
		technologies: ['Next.js', 'TypeScript', 'Tailwind CSS'],
		link: 'www.myauditor.live',
	},
	{
		id: 1,
		year: 2026,
		name: 'Click It Raffle Draw system',
		category: 'Integration',
		company: 'Udala Solutions',
		technologies: ['Next.js', 'Javascript', 'tailwind css'],
		link: 'click-it-frontend.vercel.app',
	},
	{
		id: 2,
		year: 2026,
		name: 'Rezinos',
		category: 'Integration',
		company: 'Udala Solutions',
		technologies: ['Next.js', 'Javascript', 'tailwind css', 'Framer Motion'],
		link: 'www.rezinos.com',
	},
	{
		id: 3,
		year: 2026,
		name: 'Rezino Skincare',
		category: 'Integration',
		company: 'Udala Solutions',
		technologies: ['Next js', 'Typescript', 'Redux', 'React Query'],
		link: 'www.rezino-skincare.vercel.app/',
	},
	{
		id: 4,
		year: 2025,
		name: 'Salario Marketing Page',
		category: 'Integration',
		company: 'Personal',
		technologies: ['React js', 'Bootstrap css'],
		link: 'https://salariopay.com',
	},
	{
		id: 6,
		year: 2025,
		name: 'Leewo Jones Photography',
		category: 'Design',
		company: 'Personal',
		technologies: ['React', 'Golang', 'SQLlite', 'Tailwind', 'Framer Motion'],
		link: 'www.leewo-jones.vercel.app/',
	},

	{
		id: 7,
		year: 2024,
		name: 'Faradays project',
		category: 'Design',
		company: 'Personal',
		technologies: ['React Js', 'Bootstrap CSS', 'Javascript'],
		link: 'www.faradays-projects.vercel.app',
	},
	{
		id: 8,
		year: 2024,
		name: 'Tamsey Finance Inc',
		category: 'Design',
		company: 'Personal',
		technologies: ['React js', 'Tailwind css', 'Vite'],
		link: 'www.brookfield-project.vercel.app',
	},
	{
		id: 9,
		year: 2024,
		name: 'Trevor Project',
		category: 'Design',
		company: 'Personal',
		technologies: ['React Js', 'Framer Motion', 'Tailwind CSS'],
		link: 'www.trevor-project-six.vercel.app',
	},
	{
		id: 10,
		year: 2023,
		name: 'Wfj Lawfirm',
		category: 'Design',
		company: 'Personal',
		technologies: ['React Js', 'Framer Motion', 'Tailwind CSS'],
		link: 'www.wfjlawfirm.vercel.app',
	},
];

export const experiences = [
	{
		period: 'Dec 2024 – Present',
		title: 'Frontend Engineer',
		company: 'Udala Solutions',
		companyUrl: '#',
		description:
			'Built and maintained scalable frontend solutions for multiple client products, including a lottery system and a media streaming platform. Developed responsive, user-friendly interfaces and implemented core features independently, ensuring smooth user flows and reliable performance across web applications.',
		technologies: ['React', 'TypeScript', 'JavaScript', 'HTML', 'CSS'],
	},
	{
		period: 'June 2024 – Present',
		title: 'Frontend Engineer',
		company: 'Salariopay',
		companyUrl: 'https://salariopay.com',
		description:
			'Building and maintaining user-facing features for the company\'s payroll and HR tools. Led the development of the Integration Marketplace, enabling users to explore and connect with third-party HR and finance tools. Collaborated closely with designers and backend engineers to deliver pixel-perfect, high-performance interfaces, and ensured seamless API integration, accessibility, and responsive design across devices.',
		technologies: [
			'React',
			'Redux',
			'TypeScript',
			'JavaScript',
			'Tailwind CSS',
			'jQuery',
		],
	},
	{
		period: 'Jan 2022 – June 2024',
		title: 'Software Developer',
		company: 'Metro Health HMO',
		companyUrl: 'https://metrohealthhmo.com',
		description:
			'Built core in-house software to streamline operations and improve business workflows. Developed an HR onboarding system to digitize and simplify employee intake. Collaborated with cross-functional teams to deliver scalable, user-friendly solutions.',
		technologies: ['JavaScript', 'TypeScript', 'React', 'Node.js', 'Next.js'],
	},
];
